# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # ------- Build and Test JWT-AUTH 
    - name: Build and Test JWT-AUTH
      run: | 
        cd jwt-auth
        dotnet restore
        dotnet build
        dotnet test
    - name: Build and Test JWT-AUTH
      run: | 
        cd websocket
        dotnet restore
        dotnet build
        dotnet test