# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build and Test DataStructure and Algorithms
              run: |
                  cd data-structure-algo
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test Advanced C# Concepts
              run: |
                  cd advanced-c#
                  cd HR-System
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test JWT-AUTH
              run: |
                  cd jwt-auth
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test Practical SignalR
              run: |
                  cd practical-signalR-mvc
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test SignalR Chat app
              run: |
                  cd signalR-nextjs-chat
                  cd chat-backend
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test Mailkit & SMTP
              run: |
                  cd email-mailkit-smtp
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test EF Core Relationships
              run: |
                  cd ef-core-relationships
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test Advanced LINQ
              run: |
                  cd advanced-LINQ
                  cd LINQExamples_1
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test Design Patterns
              run: |
                  cd design-patterns
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test BlazorTicTacToe (Client)
              run: |
                  cd signalR-blazor-tictactoe
                  cd BlazorTicTacToeClient
                  dotnet restore
                  dotnet build
                  dotnet test
            - name: Build and Test .NET gRPC
              run: |
                  cd dotnet-grpc
                  dotnet restore
                  dotnet build
                  dotnet test
