name: Node.js TypeScript CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Change Dir
        run: cd typescript-data-structure-algorithm

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build TypeScript
        run: yarn build
